### PR TITLE
Renovate config to automate @edx namespaced minor/patch version upgrades

### PR DESCRIPTION
**Pull request by abdullahwaheed**
### Ticket
[Create common renovate config that automates @edx namespaced minor/patch version upgrades](https://github.com/openedx/frontend-wg/issues/116)

### What has changed
Added Renovate config to update and auto merge `@edx` name spaced minor and patch packages.
Added auto merge schedule to `at any time` as overall schedule is for weekend only

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed - could you please rebase? The branch is out-of-date.

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! Just checking back in on this!

**Comment by abdullahwaheed** [comment]
@mphilbrick211 i have rebased this but `audit` workflow is failing in master as well. We have to wait for its fix to pass this PR's workflows.
Moreover, our PRs get outdated whenever someone merge something in master branch. For the time being, i'll rebase all my PRs but they will get outdate at the time of review

**Comment by arbrandes** [comment]
@abdullahwaheed, sprint check: is the audit workflow still failing in master?

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed - friendly ping on Adolfo's comment above.

**Comment by abdullahwaheed** [comment]
@mphilbrick211 rebase done. ready to review and merge

**Comment by mphilbrick211** [comment]
@abdullahwaheed thanks! Would you mind fixing the branch date error?

@arbrandes - would you mind reviewing

**Comment by arbrandes** [comment]
@pshiu, any objections here?

**Review by pshiu — APPROVED** [review]

**Pull request merged**
