### PR TITLE
feat: tutor-mfe compatiblilty for `atlas pull` | FC-0012

### PR DESCRIPTION
**Pull request by OmarIthawi**
Similar to https://github.com/openedx/frontend-app-learning/pull/1279.
## Changes

 - install atlas
 - remove `--filter` to pull all languages by default
 - use ATLAS_OPTIONS to allow custom `--filter`
 - include frontend-platform in `atlas pull`

## Refs
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by OmarIthawi** [comment]
@brian-smith-tcril the tests are complaining about Audit problems:

```
Found vulnerable allowlisted advisories: GHSA-wf5p-g6vw-rhxx.
Consider not allowlisting advisory: GHSA-hpx4-r86g-5jrg.
Found vulnerable advisory paths:
Failed security audit due to moderate vulnerabilities.
Vulnerable advisories are:
https://github.com/advisories/GHSA-jchw-25xp-jwwc
Exiting...
GHSA-jchw-25xp-jwwc|follow-redirects
Error: Process completed with exit code 1.
```

What do you suggest?

**Comment by brian-smith-tcril** [comment]
@OmarIthawi I made a PR upgrading dependencies that fixes that issue (https://github.com/openedx/frontend-app-payment/pull/848). Once that is merged this one can be rebased.

**Comment by OmarIthawi** [comment]
@brian-smith-tcril @zubair-ce07 Thanks for merging the other tests fix PR. I've rebased this PR and it's ready for merge.

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-payment&entry.867055334=https://github.com/openedx/frontend-app-payment/pull/846&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2024-02-01+17:35&entry.1917517419=2024-02-15+16:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
